/**
 * Euridian — Build/Watch mit Auto-Deploy.
 *
 *   node esbuild.config.mjs          → Watch: baut bei jeder Änderung neu und
 *                                       deployt sofort ins Vault-Plugin-Verzeichnis.
 *   node esbuild.config.mjs build    → Einmal-Produktionsbuild (minified) + Deploy.
 *
 * Nutzt die esbuild-0.13-Watch-API (`build({ watch: { onRebuild } })`). Die hält
 * den Prozess über aktive Handles am Leben — funktioniert daher auch detached im
 * Hintergrund (anders als der CLI-`--watch`, der an stdin-EOF hängt).
 */
import esbuild from "esbuild";
import process from "process";
import { deploy } from "./scripts/deploy.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "build";

/** Gemeinsame Build-Optionen. `platform: "node"` hält `require("https")` extern. */
const buildOptions = {
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	platform: "node",
	external: ["obsidian", "electron", "@codemirror", "@lezer"],
	format: "cjs",
	target: "ES6",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	outfile: "dist/main.js",
};

if (prod) {
	await esbuild.build(buildOptions);
	deploy();
	process.exit(0);
} else {
	await esbuild.build({
		...buildOptions,
		watch: {
			onRebuild(error) {
				if (error) {
					console.error("✕ Rebuild fehlgeschlagen — kein Deploy.");
					return;
				}
				console.log("↻ Rebuild ok");
				deploy();
			},
		},
	});
	// Der initiale Build ist durch (onRebuild feuert nur bei späteren Änderungen).
	deploy();
	console.log(
		"\n👀 Watch läuft — Änderungen werden gebaut + ins Vault deployt."
	);
	console.log("   In Obsidian danach Plugin neu laden. Strg+C beendet den Watch.");
}
